#!/bin/bash

spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=316 --conf spark.network.timeout=12000s --conf spark.yarn.am.memory=10g --executor-memory 22G --executor-cores 1 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/tdrive-r-sample-0.1-50x sample --diag-theta 0.32 --grid-size 0.02 --gamma 8 --num-queries 10
spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=316 --conf spark.network.timeout=12000s --conf spark.yarn.am.memory=10g --executor-memory 22G --executor-cores 1 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/tdrive-r-sample-0.2-50x sample --diag-theta 0.32 --grid-size 0.02 --gamma 8 --num-queries 10
spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=316 --conf spark.network.timeout=12000s --conf spark.yarn.am.memory=10g --executor-memory 22G --executor-cores 1 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/tdrive-r-sample-0.3-50x sample --diag-theta 0.32 --grid-size 0.02 --gamma 8 --num-queries 10
spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=316 --conf spark.network.timeout=12000s --conf spark.yarn.am.memory=10g --executor-memory 22G --executor-cores 1 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/tdrive-r-sample-0.4-50x sample --diag-theta 0.32 --grid-size 0.02 --gamma 8 --num-queries 10 --k 5
spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=316 --conf spark.network.timeout=12000s --conf spark.yarn.am.memory=10g --executor-memory 22G --executor-cores 1 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/tdrive-r-sample-0.4-50x sample --diag-theta 0.32 --grid-size 0.02 --gamma 8 --num-queries 10 --k 10
spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=316 --conf spark.network.timeout=12000s --conf spark.yarn.am.memory=10g --executor-memory 22G --executor-cores 1 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/tdrive-r-sample-0.4-50x sample --diag-theta 0.32 --grid-size 0.02 --gamma 8 --num-queries 10 --k 20
spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=316 --conf spark.network.timeout=12000s --conf spark.yarn.am.memory=10g --executor-memory 22G --executor-cores 1 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/tdrive-r-sample-0.4-50x sample --diag-theta 0.32 --grid-size 0.02 --gamma 8 --num-queries 10
