#!/bin/bash

/home/anonymous/java/spark-3.3.1-bin-hadoop2/bin/spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=3997 --conf spark.network.timeout=12000s --conf spark.memory.fraction=0.75 --conf spark.yarn.am.memory=10g --conf spark.task.cpus=1 --executor-memory 22G --executor-cores 5 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/brinkhoff-sample-0.1-50x-no-fill sample -no-timestamp -num-queries 1000
/home/anonymous/java/spark-3.3.1-bin-hadoop2/bin/spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=3997 --conf spark.network.timeout=12000s --conf spark.memory.fraction=0.75 --conf spark.yarn.am.memory=10g --conf spark.task.cpus=1 --executor-memory 22G --executor-cores 5 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/brinkhoff-sample-0.2-50x-no-fill sample -no-timestamp -num-queries 1000
/home/anonymous/java/spark-3.3.1-bin-hadoop2/bin/spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=3997 --conf spark.network.timeout=12000s --conf spark.memory.fraction=0.75 --conf spark.yarn.am.memory=10g --conf spark.task.cpus=1 --executor-memory 22G --executor-cores 5 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/brinkhoff-sample-0.3-50x-no-fill sample -no-timestamp -num-queries 1000
/home/anonymous/java/spark-3.3.1-bin-hadoop2/bin/spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=3997 --conf spark.network.timeout=12000s --conf spark.memory.fraction=0.75 --conf spark.yarn.am.memory=10g --conf spark.task.cpus=1 --executor-memory 22G --executor-cores 5 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/brinkhoff-sample-0.4-50x-no-fill sample -no-timestamp -num-queries 1000
/home/anonymous/java/spark-3.3.1-bin-hadoop2/bin/spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=3997 --conf spark.network.timeout=12000s --conf spark.memory.fraction=0.75 --conf spark.yarn.am.memory=10g --conf spark.task.cpus=1 --executor-memory 22G --executor-cores 5 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/brinkhoff-sample-0.4-50x-no-fill sample -no-timestamp -num-queries 1000 -k 5
/home/anonymous/java/spark-3.3.1-bin-hadoop2/bin/spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=3997 --conf spark.network.timeout=12000s --conf spark.memory.fraction=0.75 --conf spark.yarn.am.memory=10g --conf spark.task.cpus=1 --executor-memory 22G --executor-cores 5 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/brinkhoff-sample-0.4-50x-no-fill sample -no-timestamp -num-queries 1000 -k 10
/home/anonymous/java/spark-3.3.1-bin-hadoop2/bin/spark-submit --master yarn --deploy-mode client --class xyz.anonymous.distbfjoin.Main --name dist-bfjoin-yarn --conf spark.executor.memoryOverhead=3072 --conf spark.default.parallelism=3997 --conf spark.network.timeout=12000s --conf spark.memory.fraction=0.75 --conf spark.yarn.am.memory=10g --conf spark.task.cpus=1 --executor-memory 22G --executor-cores 5 --num-executors 24 /home/anonymous/dist-bfjoin-maven/target/dist-bfjoin-1.0-SNAPSHOT.jar /user/anonymous/augmented/brinkhoff-sample-0.4-50x-no-fill sample -no-timestamp -num-queries 1000 -k 20


